export const ALL_CHATROOMS_REQUEST = 'ALL_CHATROOMS_REQUEST'
export const ALL_CHATROOMS_SUCCESS= 'ALL_CHATROOMS_SUCCESS'
export const ALL_CHATROOMS_FAIL = 'ALL_CHATROOMS_FAIL'

export const DELETE_CHATROOM_REQUEST = 'DELETE_CHATROOM_REQUEST'
export const DELETE_CHATROOM_SUCCESS= 'DELETE_CHATROOM_SUCCESS'
export const DELETE_CHATROOM_FAIL = 'DELETE_CHATROOM_FAIL'

export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST'
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS'
export const GET_CHATS_FAIL = 'GET_CHATS_FAIL'


export const ASK_QUESTION_REQUEST = 'ASK_QUESTION_REQUSEST'
export const ASK_QUESTION_SUCCESS = 'ASK_QUESTION_SUCCESS'
export const ASK_QUESTION_FAIL = 'ASK_QUESTION_FAIL'